# Generated by Django 6.0.3 on 2026-03-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeBasicaDeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('cnes', models.CharField(max_length=7, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('endereco', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Unidade Básica de Saúde',
                'verbose_name_plural': 'Unidades Básicas de Saúde',
                'ordering': ['nome'],
            },
        ),
    ]
