# Generated by Django 6.0.3 on 2026-04-05 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
        ('user', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('paciente', 'Paciente'), ('medico_navegador', 'Médico Navegador'), ('administrador', 'Administrador')], max_length=20),
        ),
        migrations.CreateModel(
            name='MedicoNavegador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('registro_profissional', models.CharField(blank=True, max_length=50)),
                ('ubs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos_navegadores', to='unidades.unidadebasicadesaude')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mediconavegador', to='user.usuario')),
            ],
            options={
                'verbose_name': 'Médico Navegador',
                'verbose_name_plural': 'Médicos Navegadores',
            },
        ),
        migrations.DeleteModel(
            name='MedicoRegulador',
        ),
    ]
