# Generated by Django 6.0.3 on 2026-04-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usuario_tipo_usuario_mediconavegador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
