# Generated by Django 6.0.3 on 2026-04-15 00:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'CRM',
                'verbose_name_plural': 'CRMs',
            },
        ),
        migrations.CreateModel(
            name='HospitalTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('cnes', models.CharField(max_length=7, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PB', 'Paraíba')], default='PB', max_length=2)),
                ('endereco', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Hospital de Tratamento',
                'verbose_name_plural': 'Hospitais de Tratamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RetornoTeleconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=10)),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('data_realizada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Retorno de Teleconsulta',
                'verbose_name_plural': 'Retornos de Teleconsulta',
                'ordering': ['-data_agendada'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeBasicaDeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('cnes', models.CharField(max_length=7, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PB', 'Paraíba')], default='PB', max_length=2)),
                ('endereco', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Unidade Básica de Saúde',
                'verbose_name_plural': 'Unidades Básicas de Saúde',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('UBS', 'Médico da UBS'), ('ONCOLOGISTA', 'Oncologista do Programa Paraíba Contra o Câncer')], default='UBS', max_length=12)),
                ('crm', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medico', to='app.crm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ubs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='app.unidadebasicadesaude')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=150)),
                ('nome_social', models.CharField(blank=True, max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cartao_sus', models.CharField(blank=True, max_length=15, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('raca_cor', models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena'), ('nao_info', 'Não informado')], default='nao_info', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='app.unidadebasicadesaude')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_atendimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao_clinica', models.TextField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='app.paciente')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='app.unidadebasicadesaude')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data_atendimento'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('positivo', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('descricao', models.TextField()),
                ('tipo_cancer', models.CharField(blank=True, max_length=100)),
                ('data_diagnostico', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='app.hospitaltratamento')),
                ('medico', models.ForeignKey(limit_choices_to={'tipo': 'ONCOLOGISTA'}, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='app.medico')),
                ('retorno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico', to='app.retornoteleconsulta')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-data_diagnostico'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('retorno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacao_exame', to='app.retornoteleconsulta')),
            ],
            options={
                'verbose_name': 'Solicitação de Exame',
                'verbose_name_plural': 'Solicitações de Exame',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.TextField()),
                ('data_resultado', models.DateTimeField(default=django.utils.timezone.now)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resultado', to='app.solicitacaoexame')),
            ],
            options={
                'verbose_name': 'Resultado de Exame',
                'verbose_name_plural': 'Resultados de Exame',
            },
        ),
        migrations.CreateModel(
            name='Teleconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=10)),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('data_realizada', models.DateTimeField(blank=True, null=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teleconsulta', to='app.atendimento')),
            ],
            options={
                'verbose_name': 'Teleconsulta',
                'verbose_name_plural': 'Teleconsultas',
                'ordering': ['-data_agendada'],
            },
        ),
        migrations.AddField(
            model_name='solicitacaoexame',
            name='teleconsulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacao_exame', to='app.teleconsulta'),
        ),
        migrations.AddField(
            model_name='retornoteleconsulta',
            name='teleconsulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retornos', to='app.teleconsulta'),
        ),
    ]
