# Generated by Django 6.0.5 on 2026-05-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seed_demo_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='frontendrecord',
            new_name='app_fronten_kind_e1809f_idx',
            old_name='app_fronten_kind_25fe76_idx',
        ),
    ]
