# Generated by Django 6.0.3 on 2026-05-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_retornoteleconsulta_data_realizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retornoteleconsulta',
            name='data_realizada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
